# Generated by Django 5.0.1 on 2024-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="avatar.png", upload_to="avatar/"),
        ),
    ]
